url: www.pawsmonaut.games
#baseurl: /agency-jekyll-theme

# Site settings
title: Pawsmonaut Games
email: hello@pawsmonaut.games
description: "Pawsmonaut Games is a proud Scottish independent game development studio, founded in 2023 to create deep, compelling experiences without micro-transactions, battle passes or predatory monetisation."


# Team names, titles and social links
socials:
    - title: twitter
      url: http://twitter.com/Beacon_Dev

    - title: linkedin
      url: https://www.linkedin.com/in/alex-kane-60997683/

people:
- name: Alex Kane
  pic: 1
  position: Founder

- name: Apollo
  pic: 2
  position: CTO (Chief Treats Officer)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fa-brands fa-twitter
    url: http://twitter.com/Beacon_Dev
  - title: fa-solid fa-envelope
    url: mailto:hello@pawsmonaut.games
  - title: fa-brands fa-discord
    url: https://discord.gg/q95dqvKmxk


# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty